---
apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    app: application01
spec:
  containers:
    - name: nginx
      image: mirror.gcr.io/library/nginx
      ports:
        - containerPort: 80
