apiVersion: v1  
kind: Pod  
metadata:  
  name: pod-with-error2  
spec:  
  containers:  
  - name: web  
    image: mirror.gcr.io/library/nginx  
    ports:  
    - containerPort: 80  
  - name: centos  
    image: mirror.gcr.io/library/centos:7
